name: Build Languages

# Controls when the action will run.
on:

# Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
    # prevent triggering twice when pushing to a pr branch as in https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/8
    types: [opened]
  workflow_dispatch:

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'

    steps:
    - uses: actions/checkout@v2

    - name: Setup headless env
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v1.3.3
      with:
        arguments: buildLanguages
